---
- name:
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
#      username: "{{ ANSIBLE_NET_USERNAME }}"
#      password: "{{ ANSIBLE_NET_PASSWORD }}"
#      authorize: "{{ ANSIBLE_NET_AUTHORIZE }}"
#      auth_pass: "{{ ANSIBLE_NET_AUTH_PASS }}"

  tasks:
    - name: Create Network Object Group
      asa_config:
        lines:
          - object-group network {{ item }}
        provider: "{{ cli }}"
      with_items: "{{ object_group_name.splitlines() }}"
