---
- name: ASA Edit WebVPN Password
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Edit WebVPN Password
      asa_command:
        commands:
          - username {{ webvpn_username }} password {{ webvpn_password }}
        provider: "{{ cli }}"

