---
- name: Configure Static NAT on Network Object
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Configure Static NAT on Network Object
      asa_config:
        lines:
          - nat ({{ in_interface }},{{ out_interface }}) static {{ external_address }}
        parents: ['object network {{ object_name }}']
        provider: "{{ cli }}"
