---
- name: ASA Backup
  hosts: "{{ host_name }}"
  gather_facts: no
  vars:
#    remote_backup_host: 
#    remote_backup_dir: 
    cli:
      host: "{{ inventory_hostname }}"
#      username: 
#      password: 
#      authorize: 
#      auth_pass: 
      
  tasks:
    - name: Retrieve Running-Config
      asa_command:
        commands:
          - more system:running-config
        provider: "{{ cli }}"
      register: show_run

    - name: Copy Running-Config To Backup Server
      copy:
        content: '{{ show_run.stdout[0] }}'
        dest: /{{ remote_backup_dir }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%d-%m-%Y') }}.txt
      delegate_to: '{{ remote_backup_host }}'
