---
- name: ASA Ad-Hoc Commands
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Run Ad-Hoc Command
      asa_command:
        commands:
          - '{{ item }}'
        provider: "{{ cli }}"
      register: asa_command_results
      with_items: "{{ asa_adhoc_command.splitlines() }}"

    - name: Command Results
      debug:
        msg: '{{ asa_command_results.stdout }}'

