---
- name: Configure ACL
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
    eq: "{% if port_number > 0 %} eq {% else %}  {% endif %}"
#    interface_name: 
#    line: 
    line_number: "{% if line > 0 %} line {{ line }} {% else %}  {% endif %}"
#    permit_deny: 
#    acl_protocol:
#    from_host: 
#    to_host: 
#    port_number:
    cli:
      host: "{{ inventory_hostname }}"
#      username: 
#      password:
#      authorize:
#      auth_pass:

  tasks:
    - name: Configure ACL
      asa_acl:
        lines:
          - access-list {{ interface_name }} {{ line_number }} {{ permit_deny }} {{ acl_protocol }} {{ from_host }} {{ to_host }} {{ eq }} {{ port_number|default('') }}
        provider: "{{ cli }}"
