---
- name: ASA Edit WebVPN Password
  hosts: firewall
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Edit WebVPN Password
      asa_config:
        lines:
          - username {{ webvpn_username }} password {{ webvpn_password }}
        provider: "{{ cli }}"

