---
- name:
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:    
  - name: Add Host/Subnet IP To Network Object
    asa_config:
      lines:
        - {{ host_or_subnet }} {{ network_object_ipv4 }}
      parents: ['object network {{ object_name }}']
      provider: "{{ cli }}"
