---
- name: ASA Ad-Hoc Commands
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Run Ad-Hoc Command
      asa_command:
        commands:
          - '{{ asa_adhoc_command }}'
        provider: "{{ cli }}"
      register: asa_command_results

    - name: Command Results
      debug:
        msg: '{{ asa_command_results.stdout_lines[0] }}'
      when: asa_command_results is defined

