---
- name: ASA Logoff VPN User/Peer
  hosts: {{ host_name }}
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Logoff VPN User/Peer
      asa_command:
        commands:
          - vpn-sessiondb logoff '{{ vpn_session_type }}' '{{ host_or_peer }}' noconfirm
        provider: "{{ cli }}"

