---
- name:
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Create Network Object Group - Local
      asa_config:
        lines:
          - object-group network {{ vpn_group_local }}
        provider: "{{ cli }}"

    - name: Create Network Object Group - Remote
      asa_config:
        lines:
          - object-group network {{ vpn_group_remote }}
        provider: "{{ cli }}"

    - name: Add IP(s) To Network Object Group - Local
      asa_config:
        lines:
          - network-object {{ host_command|default("") }} {{ item }}
        parents: ['object-group network {{ vpn_group_local }}']
        provider: "{{ cli }}"
      with_items: "{{ vpn_group_local_ipv4.splitlines() }}"

    - name: Add IP(s) To Network Object Group - Remote
      asa_config:
        lines:
          - network-object {{ host_command|default("") }} {{ item }}
        parents: ['object-group network {{ vpn_group_remote }}']
        provider: "{{ cli }}"
      with_items: "{{ vpn_group_remote_ipv4.splitlines() }}"

    - name: Configure ACL
      asa_acl:
        lines:
          - access-list {{ vpn_acl_group }} permit ip object-group {{ vpn_group_local }} object-group {{ vpn_group_remote }}
        provider: "{{ cli }}"

    - name: Create Crypto Map
      asa_config:
        lines:
          - crypto map outside-crypt {{ crypt_number }} match address {{ vpn_acl_group }}
          - crypto map outside-crypt {{ crypt_number }} set peer {{ vpn_peer_ip }}
          - crypto map outside-crypt {{ crypt_number }} set ikev1 transform-set {{ vpn_encrypt_alg }}
          - crypto map outside-crypt {{ crypt_number }} set security-association lifetime seconds {{ vpn_lifetime_sec }}
        provider: "{{ cli }}"

    - name: Create Tunnel Group
      asa_config:
        lines:
          - tunnel-group {{ vpn_peer_ip }} type ipsec-l2l
          - tunnel-group {{ vpn_peer_ip }} ipsec-attributes
          - pre-shared-key {{ vpn_psk }}
        provider: "{{ cli }}"

