---
- name: Cisco ASA Test
  hosts: firewall
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: zgould
      password: '@R3birth!!'
      authorize: yes
      auth_pass: '@R3birth!!'
  
  tasks:
    - name: Get Output
      asa_command:
        commands:
          - show version
        provider: "{{ cli }}"
      register: result
      
    - debug: msg="{{ result.stdout[0] }}"
