---
- name: ASA Backup
  hosts: "{{ host_name }}"
  gather_facts: no
  connection: local
  vars:
#    backup_directory:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
    - name: Retrieve Running-Config
      asa_command:
        commands:
          - more system:running-config
        provider: "{{ cli }}"
      register: show_run

    - name: Copy Running-Config To Backup Directory
      copy:
        content: '{{ show_run.stdout[0] }}'
        dest: /{{ backup_directory }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%d-%m-%Y') }}.txt
